hh_elec_power<-read.table("household_power_consumption.txt",sep="；",header=TRUE,as.is = TRUE, na.strings="?")
hh_elec_power$Date<-as.Date(hh_elec_power$Date,format='%d/%m/%Y')
hh_data_subset<-subset(hh_elec_power, Date=="2007-2-1"|Date=="2007-2-2")
hh_data_subset$Datetime<-as.POSIXct(paste(hh_data_subset$Date,hh_data_subset$Time))
png("plot4.png", width=480, height=480)
par(mfcol=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(hh_data_subset, {
  plot(x=Datetime,y=Global_active_power,type="l",xlab="",ylab="Global Active Power")
  plot(Datetime, Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering")
  points(Datetime, Sub_metering_1, type = "l", col="black")
  points(Datetime, Sub_metering_2, type = "l", col="red")
  points(Datetime, Sub_metering_3, type = "l", col="blue")
  legend("topright", pch = "___", col = c("black", "red", "blue"), legend= c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
  plot(x=Datetime,y=Voltage,type="l",xlab="datetime",ylab="Voltage")
  plot(x=Datetime,y=Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
})
dev.off()