hh_elec_power<-read.table("household_power_consumption.txt",sep="；",header=TRUE,as.is = TRUE, na.strings="?")
hh_elec_power$Date<-as.Date(hh_elec_power$Date,format='%d/%m/%Y')
hh_data_subset<-subset(hh_elec_power, Date=="2007-2-1"|Date=="2007-2-2")
hh_data_subset$Datetime<-as.POSIXct(paste(hh_data_subset$Date,hh_data_subset$Time))
png("plot3.png", width=480, height=480)
plot(hh_data_subset$Datetime, hh_data_subset$Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering")
points(hh_data_subset$Datetime, hh_data_subset$Sub_metering_1, type = "l", col="black")
points(hh_data_subset$Datetime, hh_data_subset$Sub_metering_2, type = "l", col="red")
points(hh_data_subset$Datetime, hh_data_subset$Sub_metering_3, type = "l", col="blue")
legend("topright", pch = "___", col = c("black", "red", "blue"), legend= c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()